# Generated by Django 3.2.12 on 2022-02-06 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=255)),
                ('appointment_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(default=datetime.date.today)),
                ('date_modified', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('date', models.DateField()),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.installation')),
            ],
        ),
    ]
