# Generated by Django 3.2.12 on 2022-02-06 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='installation',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='installation',
            name='date_modified',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
