# Generated by Django 3.2.12 on 2022-02-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20220206_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Rejected', 'Rejected')], default='Requested', max_length=20),
        ),
    ]
