# Generated by Django 3.2.12 on 2022-02-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Rejected', 'Rejected')], default='Requested', max_length=20),
        ),
    ]
