# Generated by Django 3.2.12 on 2022-02-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20220206_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Installation Requested', 'Requested'), ('Installation In Progress', 'In Progress'), ('Instalation Complete', 'Complete'), ('Instalation Rejected', 'Rejected')], default='Installation Requested', max_length=40),
        ),
    ]
